/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.eltex;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());

        User user = new User(1, "Alex");
        System.out.println(user.toString());

        ObjectMapper mapper = new ObjectMapper();
//        mapper.writeValue(new File("result.json"), user);

        User user1 = mapper.readValue(new File("result.json"), User.class);
        System.out.println(user1.toString());
    }
}
